apiVersion: v1
kind: Service
metadata:
  name: {{ include "cyber-accountant.fullname" . }}
  labels:
    {{- include "cyber-accountant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "cyber-accountant.selectorLabels" . | nindent 4 }}
