import { useEffect, useState, type FormEvent } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useQuery } from '@tanstack/react-query';

import { ConfirmDialog } from '@/components/ConfirmDialog';
import { DataTable, type Column } from '@/components/DataTable';
import { FormField } from '@/components/FormField';
import { PaginationFooter } from '@/components/PaginationFooter';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { useToast } from '@/components/ui/toaster';
import { useApiMutation } from '@/hooks/useApiMutation';
import { useErrorToast } from '@/hooks/useErrorToast';
import { useMe } from '@/hooks/useMe';
import { usePagedQuery } from '@/hooks/usePagedQuery';
import { api } from '@/lib/api/client';
import { getSelectedOrgId, setSelectedOrgId } from '@/lib/api/orgSession';
import { qk } from '@/lib/api/queryKeys';
import type {
  MembersListResponse,
  MemberWithEmail,
  MineOrganizationsResponse,
  Organization,
  OrganizationDetailResponse,
  OrganizationListResponse,
  OrganizationWithRole,
  OrgMemberDetailResponse,
  SwitchResponse,
} from '@/lib/api/types';
import { userIsAdmin } from '@/lib/auth/permissions';
import {
  addOrgMemberByEmailSchema,
  createOrganizationSchema,
  type AddOrgMemberByEmailValues,
  type CreateOrganizationValues,
} from '@/lib/schemas/orgs';

const PER_PAGE = 20;
const ORG_ROLES = ['owner', 'accountant', 'viewer'] as const;
type OrgRole = (typeof ORG_ROLES)[number];

/**
 * OrganizationsPage — generated by scripts/new-react-page.sh, filled in
 * for Task 8. Route: /organizations (guard: confirmed).
 *
 * Two audiences share this page:
 *   - Admins see every tenant (GET /api/v1/orgs) plus a create form
 *     (POST /api/v1/orgs) — tenants are provisioned by a system admin,
 *     not self-service (design spec §5).
 *   - Everyone sees their own memberships (GET /api/v1/orgs/mine) and can
 *     switch into one (POST /api/v1/orgs/{id}/switch).
 *
 * Session mechanics: this template's auth is cookie-only (client.ts's
 * `credentials: 'include'`, no Bearer token in memory/localStorage), and
 * /switch sets the __Host-access cookie itself — there is no token to
 * copy out of the response body, so onSuccess below does the cookie-mode
 * equivalent of what useLogin does for the login flow: it updates the
 * client's own bookkeeping (orgSession's selected-org id) instead of a
 * token store, and lets TanStack Query re-render off that. See
 * lib/api/orgSession.ts and client.ts's tryRefresh for the other half —
 * replaying /switch after every refresh, since a bare refresh resets the
 * org claim to the single-membership default (docs/openapi.yaml).
 */
export function OrganizationsPage() {
  const me = useMe();
  const isAdmin = userIsAdmin(me.data);
  const toast = useToast();

  // Our own record of "the org whose access token is currently live" —
  // see orgSession.ts. Seeded from localStorage so a reload doesn't
  // forget a prior switch.
  const [activeOrgId, setActiveOrgId] = useState<string | null>(() => getSelectedOrgId());

  const mineQ = useQuery({
    queryKey: qk.orgs.mine(),
    queryFn: () => api.getJson<MineOrganizationsResponse>('/api/v1/orgs/mine'),
  });

  // Mirror the backend's single-membership default: mint_session sets the
  // `org` claim on login/refresh to the caller's sole organization with no
  // /switch call needed, when they belong to exactly one. Adopt that same
  // default client-side so the member-management gate below isn't overly
  // strict for the common single-tenant case.
  useEffect(() => {
    if (activeOrgId) return;
    const mine = mineQ.data?.data;
    if (mine && mine.length === 1) {
      setSelectedOrgId(mine[0].id);
      setActiveOrgId(mine[0].id);
    }
  }, [activeOrgId, mineQ.data]);

  const switchOrg = useApiMutation(
    (id: string) => api.postJson<SwitchResponse>(`/api/v1/orgs/${id}/switch`),
    {
      invalidate: [qk.orgs.mine()],
      onSuccess: (_data, id) => {
        setSelectedOrgId(id);
        setActiveOrgId(id);
        toast.success('Switched active organization.');
      },
    },
  );
  useErrorToast(switchOrg.error);

  const mineColumns: Column<OrganizationWithRole>[] = [
    { header: 'Name', className: 'font-medium', cell: (o) => o.name },
    { header: 'BIN', className: 'font-mono', cell: (o) => o.bin },
    { header: 'Role', className: 'capitalize', cell: (o) => o.role },
    {
      header: 'Active',
      cell: (o) =>
        o.id === activeOrgId ? (
          <span className="text-emerald-600 dark:text-emerald-400" aria-label="Active">
            ✓
          </span>
        ) : (
          <span className="text-muted-foreground" aria-hidden="true">
            —
          </span>
        ),
    },
    {
      header: '',
      className: 'text-right',
      cell: (o) => (
        <Button
          size="sm"
          variant={o.id === activeOrgId ? 'outline' : 'default'}
          disabled={o.id === activeOrgId || switchOrg.isPending}
          onClick={() => switchOrg.mutate(o.id)}
        >
          {o.id === activeOrgId ? 'Working here' : 'Work in this organization'}
        </Button>
      ),
    },
  ];

  return (
    <div className="container mx-auto max-w-4xl py-8 space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Organizations</h1>
        <p className="text-sm text-muted-foreground">
          Switch which organization your session is scoped to, and manage its members.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>My organizations</CardTitle>
          <CardDescription>
            Organizations you belong to, and the role you hold in each.
          </CardDescription>
        </CardHeader>
        <CardContent className="overflow-x-auto">
          <DataTable
            columns={mineColumns}
            rows={mineQ.data?.data}
            rowKey={(o) => o.id}
            isLoading={mineQ.isLoading}
            error={mineQ.error}
            emptyText="You are not a member of any organization yet."
          />
        </CardContent>
      </Card>

      {mineQ.data && mineQ.data.data.length > 0 && (
        <MemberManagementCard
          organizations={mineQ.data.data}
          isAdmin={isAdmin}
          activeOrgId={activeOrgId}
        />
      )}

      {isAdmin && <AdminOrganizationsSection />}
    </div>
  );
}

/**
 * Admin-only: every tenant, paginated, plus the create-organization form.
 * Tenants are provisioned by a system admin (design spec §5) — there is no
 * self-service org creation, hence this section is gated on Administer.
 */
function AdminOrganizationsSection() {
  const [creating, setCreating] = useState(false);
  const { data, isLoading, error, isPlaceholderData, page, setPage, totalPages } = usePagedQuery({
    queryKey: qk.orgs.all(),
    queryFn: ({ limit, offset }) =>
      api.getJson<OrganizationListResponse>('/api/v1/orgs', { query: { limit, offset } }),
    perPage: PER_PAGE,
  });

  const create = useApiMutation(
    (values: CreateOrganizationValues) =>
      api.postJson<OrganizationDetailResponse>('/api/v1/orgs', { body: values }),
    {
      invalidate: [qk.orgs.all()],
      onSuccess: () => setCreating(false),
    },
  );
  useErrorToast(create.error);

  const columns: Column<Organization>[] = [
    { header: 'Name', className: 'font-medium', cell: (o) => o.name },
    { header: 'BIN', className: 'font-mono', cell: (o) => o.bin },
    { header: 'Tax regime', cell: (o) => o.tax_regime },
    {
      header: 'VAT payer',
      cell: (o) => (
        <span aria-label={o.vat_payer ? 'VAT payer' : 'Not a VAT payer'}>
          <span aria-hidden="true">{o.vat_payer ? '✓' : '—'}</span>
        </span>
      ),
    },
    { header: 'Status', className: 'capitalize', cell: (o) => o.status },
  ];

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0">
        <div>
          <CardTitle>{data ? `${data.total} organization(s)` : 'All organizations'}</CardTitle>
          <CardDescription>Admin view — every tenant in the system.</CardDescription>
        </div>
        <Button onClick={() => setCreating(true)}>New organization</Button>
      </CardHeader>
      <CardContent className="overflow-x-auto">
        <DataTable
          columns={columns}
          rows={data?.data}
          rowKey={(o) => o.id}
          isLoading={isLoading}
          error={error}
          emptyText="No organizations yet."
          isPlaceholder={isPlaceholderData}
        />
        {data && (
          <PaginationFooter
            page={page}
            totalPages={totalPages}
            isPlaceholderData={isPlaceholderData}
            onPageChange={setPage}
          />
        )}
      </CardContent>
      {creating && (
        <CardContent className="border-t pt-6">
          <CreateOrganizationForm
            submitting={create.isPending}
            onSubmit={(values) => create.mutate(values)}
            onCancel={() => setCreating(false)}
          />
        </CardContent>
      )}
    </Card>
  );
}

function CreateOrganizationForm({
  submitting,
  onSubmit,
  onCancel,
}: {
  submitting: boolean;
  onSubmit: (values: CreateOrganizationValues) => void;
  onCancel: () => void;
}) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateOrganizationValues>({
    resolver: zodResolver(createOrganizationSchema),
    defaultValues: { bin: '', name: '', tax_regime: 'snr_simplified', vat_payer: false },
  });

  return (
    <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <FormField
          id="org-bin"
          label="BIN/IIN (12 digits)"
          error={errors.bin?.message}
          {...register('bin')}
        />
        <FormField id="org-name" label="Name" error={errors.name?.message} {...register('name')} />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-2">
          <Label htmlFor="org-tax-regime">Tax regime</Label>
          <select
            id="org-tax-regime"
            className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
            {...register('tax_regime')}
          >
            <option value="snr_simplified">SNR simplified</option>
            <option value="standard">Standard</option>
          </select>
        </div>
        <div className="flex items-center gap-2 pt-8">
          <input id="org-vat-payer" type="checkbox" {...register('vat_payer')} />
          <label htmlFor="org-vat-payer" className="text-sm">
            VAT payer
          </label>
        </div>
      </div>
      <div className="flex gap-2">
        <Button type="submit" disabled={submitting}>
          {submitting ? 'Creating…' : 'Create organization'}
        </Button>
        <Button type="button" variant="ghost" onClick={onCancel}>
          Cancel
        </Button>
      </div>
    </form>
  );
}

/**
 * Member management: roster (GET /orgs/{id}/members, email + role per row,
 * inline role-select -> PATCH, remove -> DELETE) plus an add-by-email form
 * (POST /orgs/{id}/members with {email, role} — resolved server-side via
 * Repositories::UserRepository::find_by_email, 404 if nobody's registered
 * with that address yet).
 *
 * Gate (mirrors OrganizationsController's require_admin_or_org_owner,
 * fail-closed by design): a full admin can manage any organization's
 * members regardless of their active org; a non-admin owner can only
 * manage the ORGANIZATION THEY ARE CURRENTLY WORKING IN (activeOrgId) —
 * an owner of org B sitting in org A's context is not authorized on the
 * backend until they switch, so the control is hidden rather than shown
 * disabled-and-failing.
 */
function MemberManagementCard({
  organizations,
  isAdmin,
  activeOrgId,
}: {
  organizations: OrganizationWithRole[];
  isAdmin: boolean;
  activeOrgId: string | null;
}) {
  const manageable = organizations.filter(
    (o) => isAdmin || (o.role === 'owner' && o.id === activeOrgId),
  );
  const [selectedOrgId, setSelectedOrgIdState] = useState<string>(manageable[0]?.id ?? '');

  useEffect(() => {
    if (manageable.length > 0 && !manageable.some((o) => o.id === selectedOrgId)) {
      setSelectedOrgIdState(manageable[0].id);
    }
  }, [manageable, selectedOrgId]);

  if (manageable.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Manage members</CardTitle>
          <CardDescription>
            Switch into an organization you own to manage its members (or ask an admin).
          </CardDescription>
        </CardHeader>
      </Card>
    );
  }

  const selectedOrg = manageable.find((o) => o.id === selectedOrgId) ?? manageable[0];

  return (
    <Card>
      <CardHeader>
        <CardTitle>Manage members</CardTitle>
        <CardDescription>
          View the roster, add someone by email, re-role, or remove a member.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {manageable.length > 1 && (
          <div className="space-y-2">
            <Label htmlFor="manage-org">Organization</Label>
            <select
              id="manage-org"
              className="flex h-10 w-full max-w-sm rounded-md border border-input bg-background px-3 py-2 text-sm"
              value={selectedOrgId}
              onChange={(e) => setSelectedOrgIdState(e.target.value)}
            >
              {manageable.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.name}
                </option>
              ))}
            </select>
          </div>
        )}
        <MemberActions orgId={selectedOrg.id} />
      </CardContent>
    </Card>
  );
}

function MemberActions({ orgId }: { orgId: string }) {
  const toast = useToast();

  const rosterQ = useQuery({
    queryKey: qk.orgs.members(orgId),
    queryFn: () => api.getJson<MembersListResponse>(`/api/v1/orgs/${orgId}/members`),
  });

  const [addEmail, setAddEmail] = useState('');
  const [addRole, setAddRole] = useState<OrgRole>('viewer');
  const [emailError, setEmailError] = useState<string | undefined>(undefined);
  const [removingMember, setRemovingMember] = useState<MemberWithEmail | null>(null);

  const addMember = useApiMutation(
    (vars: AddOrgMemberByEmailValues) =>
      api.postJson<OrgMemberDetailResponse>(`/api/v1/orgs/${orgId}/members`, { body: vars }),
    {
      invalidate: [qk.orgs.members(orgId)],
      onSuccess: () => {
        setAddEmail('');
        setAddRole('viewer');
        toast.success('Member added.');
      },
    },
  );
  const changeRole = useApiMutation(
    (vars: { userId: string; role: OrgRole }) =>
      api.patchJson<OrgMemberDetailResponse>(`/api/v1/orgs/${orgId}/members/${vars.userId}`, {
        body: { role: vars.role },
      }),
    {
      invalidate: [qk.orgs.members(orgId)],
      onSuccess: () => toast.success('Role updated.'),
    },
  );
  const removeMember = useApiMutation(
    (userId: string) => api.deleteJson(`/api/v1/orgs/${orgId}/members/${userId}`),
    {
      invalidate: [qk.orgs.members(orgId)],
      onSuccess: () => {
        setRemovingMember(null);
        toast.success('Member removed.');
      },
    },
  );
  // 404 user_not_found on the add-by-email path surfaces here too — the
  // backend's message ("No user with this email — ask them to register
  // first") rides straight through apiErrorMessage into the toast.
  useErrorToast(addMember.error ?? changeRole.error ?? removeMember.error);

  const handleAdd = (e: FormEvent) => {
    e.preventDefault();
    const parsed = addOrgMemberByEmailSchema.safeParse({ email: addEmail, role: addRole });
    if (!parsed.success) {
      setEmailError(parsed.error.issues[0]?.message ?? 'Invalid email');
      return;
    }
    setEmailError(undefined);
    addMember.mutate(parsed.data);
  };

  const columns: Column<MemberWithEmail>[] = [
    { header: 'Email', className: 'font-medium', cell: (m) => m.email },
    {
      header: 'Role',
      cell: (m) => (
        <select
          aria-label={`Role for ${m.email}`}
          className="flex h-9 rounded-md border border-input bg-background px-2 py-1 text-sm capitalize"
          value={m.role}
          disabled={changeRole.isPending}
          onChange={(e) =>
            changeRole.mutate({ userId: m.user_id, role: e.target.value as OrgRole })
          }
        >
          {ORG_ROLES.map((r) => (
            <option key={r} value={r}>
              {r}
            </option>
          ))}
        </select>
      ),
    },
    {
      header: '',
      className: 'text-right',
      cell: (m) => (
        <Button size="sm" variant="destructive" onClick={() => setRemovingMember(m)}>
          Remove
        </Button>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h3 className="mb-2 text-sm font-medium">Members</h3>
        <DataTable
          columns={columns}
          rows={rosterQ.data?.data}
          rowKey={(m) => m.user_id}
          isLoading={rosterQ.isLoading}
          error={rosterQ.error}
          emptyText="No members yet."
        />
      </div>

      <form className="space-y-3" onSubmit={handleAdd}>
        <h3 className="text-sm font-medium">Add member</h3>
        <div className="flex flex-wrap items-end gap-3">
          <FormField
            id="add-email"
            label="Email"
            type="email"
            value={addEmail}
            error={emailError}
            onChange={(e) => {
              setAddEmail(e.target.value);
              if (emailError) setEmailError(undefined);
            }}
            className="max-w-xs"
          />
          <div className="space-y-2">
            <Label htmlFor="add-role">Role</Label>
            <select
              id="add-role"
              className="flex h-10 rounded-md border border-input bg-background px-3 py-2 text-sm"
              value={addRole}
              onChange={(e) => setAddRole(e.target.value as OrgRole)}
            >
              {ORG_ROLES.map((r) => (
                <option key={r} value={r}>
                  {r}
                </option>
              ))}
            </select>
          </div>
          <Button type="submit" disabled={addMember.isPending || !addEmail.trim()}>
            {addMember.isPending ? 'Adding…' : 'Add'}
          </Button>
        </div>
      </form>

      {removingMember && (
        <ConfirmDialog
          title="Remove member"
          description={`Remove ${removingMember.email} from this organization? This cannot be undone.`}
          confirmLabel="Remove member"
          destructive
          busy={removeMember.isPending}
          onConfirm={() => removeMember.mutate(removingMember.user_id)}
          onClose={() => setRemovingMember(null)}
        />
      )}
    </div>
  );
}
