// Golden vectors below were generated by an independent python3
// reimplementation of the same 9-step formula (see task-2-brief.md and
// PayrollCalculator.hpp's file header for the order of calculation and its
// sources). Rates/constants match the Task 1 seed in
// migrations/011_tax_reference.sql (2026 values).
#include <gtest/gtest.h>

#include "payroll/PayrollCalculator.hpp"

namespace {

Payroll::Rates make_rates() {
    Payroll::Rates r;
    r.ipn_bp = 1000;
    r.opv_bp = 1000;
    r.opvr_bp = 350;
    r.so_bp = 500;
    r.osms_bp = 300;
    r.vosms_bp = 200;
    r.social_tax_bp = 600;
    r.mrp_tiyn = 432500;
    r.mzp_tiyn = 8500000;
    r.ipn_deduction_mrp = 30;
    r.opv_base_max_mzp = 50;
    r.so_base_min_mzp = 1;
    r.so_base_max_mzp = 7;
    r.vosms_base_max_mzp = 20;
    r.osms_base_max_mzp = 40;
    r.social_tax_applies = true;
    return r;
}

}  // namespace

TEST(PayrollCalculator, ApplyBpRoundsHalfUp) {
    EXPECT_EQ(Payroll::apply_bp(333, 1000), 33);
    EXPECT_EQ(Payroll::apply_bp(335, 1000), 34);
}

// (a) 85 000 tg (= 1 MZP) with IPN deduction claimed.
TEST(PayrollCalculator, GoldenCaseA_OneMzpWithDeduction) {
    const auto rates = make_rates();
    Payroll::Input in;
    in.gross_tiyn = 8500000;
    in.ipn_deduction_claimed = true;
    in.opvr_exempt = false;

    const auto out = Payroll::calculate(in, rates);

    EXPECT_EQ(out.opv, 850000);
    EXPECT_EQ(out.vosms, 170000);
    EXPECT_EQ(out.ipn, 0);
    EXPECT_EQ(out.net, 7480000);
    EXPECT_EQ(out.opvr, 297500);
    EXPECT_EQ(out.so, 425000);
    EXPECT_EQ(out.osms, 255000);
    EXPECT_EQ(out.social_tax, 448800);
    EXPECT_EQ(out.employer_cost_total, 9926300);
}

// (b) 300 000 tg with IPN deduction claimed.
TEST(PayrollCalculator, GoldenCaseB_300kWithDeduction) {
    const auto rates = make_rates();
    Payroll::Input in;
    in.gross_tiyn = 30000000;
    in.ipn_deduction_claimed = true;
    in.opvr_exempt = false;

    const auto out = Payroll::calculate(in, rates);

    EXPECT_EQ(out.opv, 3000000);
    EXPECT_EQ(out.vosms, 600000);
    EXPECT_EQ(out.ipn, 1342500);
    EXPECT_EQ(out.net, 25057500);
    EXPECT_EQ(out.opvr, 1050000);
    EXPECT_EQ(out.so, 1350000);
    EXPECT_EQ(out.osms, 900000);
    EXPECT_EQ(out.social_tax, 1584000);
    EXPECT_EQ(out.employer_cost_total, 34884000);
}

// (c) 300 000 tg without IPN deduction.
TEST(PayrollCalculator, GoldenCaseC_300kWithoutDeduction) {
    const auto rates = make_rates();
    Payroll::Input in;
    in.gross_tiyn = 30000000;
    in.ipn_deduction_claimed = false;
    in.opvr_exempt = false;

    const auto out = Payroll::calculate(in, rates);

    EXPECT_EQ(out.opv, 3000000);
    EXPECT_EQ(out.vosms, 600000);
    EXPECT_EQ(out.ipn, 2640000);
    EXPECT_EQ(out.net, 23760000);
    EXPECT_EQ(out.opvr, 1050000);
    EXPECT_EQ(out.so, 1350000);
    EXPECT_EQ(out.osms, 900000);
    EXPECT_EQ(out.social_tax, 1584000);
    EXPECT_EQ(out.employer_cost_total, 34884000);
}

// (d) 1 000 000 tg — exercises the SO base ceiling (7 MZP).
TEST(PayrollCalculator, GoldenCaseD_MillionSoCeiling) {
    const auto rates = make_rates();
    Payroll::Input in;
    in.gross_tiyn = 100000000;
    in.ipn_deduction_claimed = true;
    in.opvr_exempt = false;

    const auto out = Payroll::calculate(in, rates);

    EXPECT_EQ(out.opv, 10000000);
    EXPECT_EQ(out.vosms, 2000000);
    EXPECT_EQ(out.ipn, 7502500);
    EXPECT_EQ(out.net, 80497500);
    EXPECT_EQ(out.opvr, 3500000);
    EXPECT_EQ(out.so, 2975000);
    EXPECT_EQ(out.osms, 3000000);
    EXPECT_EQ(out.social_tax, 5280000);
    EXPECT_EQ(out.employer_cost_total, 114755000);
}

// (e) 60 000 tg — below 1 MZP, exercises the SO base floor (1 MZP).
TEST(PayrollCalculator, GoldenCaseE_BelowMzpSoFloor) {
    const auto rates = make_rates();
    Payroll::Input in;
    in.gross_tiyn = 6000000;
    in.ipn_deduction_claimed = true;
    in.opvr_exempt = false;

    const auto out = Payroll::calculate(in, rates);

    EXPECT_EQ(out.opv, 600000);
    EXPECT_EQ(out.vosms, 120000);
    EXPECT_EQ(out.ipn, 0);
    EXPECT_EQ(out.net, 5280000);
    EXPECT_EQ(out.opvr, 210000);
    EXPECT_EQ(out.so, 425000);
    EXPECT_EQ(out.osms, 180000);
    EXPECT_EQ(out.social_tax, 316800);
    EXPECT_EQ(out.employer_cost_total, 7131800);
}

// НК РК ст.363 defines a progressive ИПН scale (10% up to 8500 МРП/year
// cumulative income, 15% above — on 2026 constants that's ~3.06M tg/month).
// P2's calculate() deliberately stays single-rate: it has no year-to-date
// income context to compute the cumulative threshold against. This test
// pins that documented gap for a salary well past the annual threshold —
// when year-to-date tracking is added, this test (and Rates::ipn_bp's flat
// application at Step 3) must be intentionally rewritten, not silently
// left passing on the old single-rate assumption.
TEST(PayrollCalculator, HighSalaryStillUsesFlatRateInP2) {
    const auto rates = make_rates();
    Payroll::Input in;
    in.gross_tiyn = 500000000;  // 5 000 000 tg/month, far above the 8500 MRP/year threshold
    in.ipn_deduction_claimed = true;
    in.opvr_exempt = false;

    const auto out = Payroll::calculate(in, rates);

    EXPECT_EQ(out.opv, 42500000);
    EXPECT_EQ(out.vosms, 3400000);
    // Flat 10% throughout ipn_base, NOT the 15% marginal rate the real
    // progressive scale would apply above the annual threshold.
    EXPECT_EQ(out.ipn, 44112500);
    EXPECT_EQ(out.net, 409987500);
    EXPECT_EQ(out.opvr, 14875000);
    EXPECT_EQ(out.so, 2975000);
    EXPECT_EQ(out.osms, 10200000);
    EXPECT_EQ(out.social_tax, 27246000);
    EXPECT_EQ(out.employer_cost_total, 555296000);
}

TEST(PayrollCalculator, SocialTaxSkippedOnSnr) {
    auto rates = make_rates();
    rates.social_tax_applies = false;
    Payroll::Input in;
    in.gross_tiyn = 30000000;

    const auto out = Payroll::calculate(in, rates);

    EXPECT_EQ(out.social_tax, 0);
    // employer_cost_total should not include the skipped social tax.
    EXPECT_EQ(out.employer_cost_total, in.gross_tiyn + out.opvr + out.so + out.osms);
}

TEST(PayrollCalculator, OpvrExemptZero) {
    const auto rates = make_rates();
    Payroll::Input in;
    in.gross_tiyn = 30000000;
    in.opvr_exempt = true;

    const auto out = Payroll::calculate(in, rates);

    EXPECT_EQ(out.opvr, 0);
}

TEST(PayrollCalculator, SoBaseFloorApplies) {
    const auto rates = make_rates();
    Payroll::Input in;
    in.gross_tiyn = 6000000;  // 60 000 tg, below 1 MZP (85 000 tg)

    const auto out = Payroll::calculate(in, rates);

    // Floor: so_base clamped up to 1 MZP = 8 500 000 tiyn -> so = 5%.
    const long long expected_so_base = rates.mzp_tiyn * rates.so_base_min_mzp;
    EXPECT_EQ(out.so, Payroll::apply_bp(expected_so_base, rates.so_bp));
    EXPECT_EQ(out.so, 425000);
}

TEST(PayrollCalculator, CeilingsApply) {
    const auto rates = make_rates();
    Payroll::Input in;
    // 5 000 000 tg — above ALL four ceilings: OPV/OPVR cap at 50 MZP =
    // 4 250 000 tg, OSMS caps at 40 MZP = 3 400 000 tg, and gross - OPV
    // (well past those two) still exceeds the SO cap of 7 MZP = 595 000 tg.
    // (1 000 000 tg, used previously, is BELOW the OPV/OPVR/OSMS ceilings —
    // only the SO ceiling would be exercised there; see fix round 1.)
    in.gross_tiyn = 500000000;

    const auto out = Payroll::calculate(in, rates);

    // OPV/OPVR base capped at 50 MZP; SO base capped at 7 MZP (after
    // subtracting OPV); OSMS base capped at 40 MZP.
    const long long opv_ceiling = rates.mzp_tiyn * rates.opv_base_max_mzp;
    const long long so_ceiling = rates.mzp_tiyn * rates.so_base_max_mzp;
    const long long osms_ceiling = rates.mzp_tiyn * rates.osms_base_max_mzp;

    EXPECT_EQ(out.opv, Payroll::apply_bp(opv_ceiling, rates.opv_bp));
    EXPECT_EQ(out.opvr, Payroll::apply_bp(opv_ceiling, rates.opvr_bp));
    EXPECT_EQ(out.so, Payroll::apply_bp(so_ceiling, rates.so_bp));
    EXPECT_EQ(out.osms, Payroll::apply_bp(osms_ceiling, rates.osms_bp));
}
